services:
  # run react-client-prod build on Port 80
  react-client:
    image: docker_username/csl-react-client
    build:
      context: .
      dockerfile: ./apps/react-client/Dockerfile
    ports:
      - '3000:80'

  next-client:
    image: docker_username/csl-next-client
    build:
      context: .
      dockerfile: ./apps/next-client/Dockerfile
    ports:
      - '3000:3000'

  express-server:
    image: docker_username/csl-express-server
    build:
      context: .
      dockerfile: ./apps/express-server/Dockerfile
    ports:
      - '8000:8000'

  # somehow port mapping not working for this
  nestjs-server:
    image: docker_username/csl-nestjs-server
    build:
      context: .
      dockerfile: ./apps/nestjs-server/Dockerfile
    ports:
      - '4000:4000'
