# Run Production Builds of all apps.
services:
  express-server:
    image: docker_username/csl-express-server
    build:
      context: .
      dockerfile: ./apps/express-server/Dockerfile
    ports:
      - '8000:8000'

  # somehow port mapping not working for this
  nestjs-server:
    image: docker_username/csl-nestjs-server
    build:
      context: .
      dockerfile: ./apps/nestjs-server/Dockerfile
    ports:
      - '4000:4000'

  next-client:
    image: docker_username/csl-next-client
    build:
      context: .
      dockerfile: ./apps/next-client/Dockerfile
    ports:
      - '3001:3000'

  react-client:
    image: docker_username/csl-react-client
    build:
      context: .
      dockerfile: ./apps/react-client/Dockerfile
    ports:
      - '3000:80'


