/**
 * List of prefixes Stripe adds in front of its ids to
 * better differentiate between different types of objects.
 *
 * - For COUPONS, there is no prefix in id,
 *   eg -> "id": "jMT0WJUD",
 */
export enum StripePrefixes {
  BALANCE_TRANSACTION = 'txn_',
  BANK_ACCOUNT = 'ba_',
  CARD = 'card_',
  CASH_BALANCE_TRANSACTION = 'ccsbtxn_',
  CHARGE = 'ch_',
  CONFIRMATION_TOKEN = 'ctoken_',
  CUSTOMER = 'cus_',
  CVC_TOKEN = 'cvctok_',
  DISCOUNT = 'di_',
  DISPUTE = 'du_',
  EVENT = 'evt_',
  FILE = 'file_',
  FILE_LINK = 'link_',
  INVOICE = 'iv_',
  MANDATE = 'mandate_',
  PAYMENT_INTENT = 'pi_',
  PAYMENT_METHOD = 'pm_',
  PAYMENT_METHOD_CONFIGURATION = 'pmc_',
  PAYMENT_METHOD_DOMAIN = 'pmd_',
  PAYMENT_LINK = 'plink_',
  PAYOUT = 'po_',
  PERSON_TOKEN = 'cpt_',
  PII_TOKEN = 'pii_',
  PRICE = 'price_',
  PRODUCT = 'prod_',
  PROMOTION_CODE = 'promo_',
  REFUND = 're_',
  SETUP_ATTEMPT = 'setatt_',
  SETUP_INTENT = 'seti_',
  SHIPPING_RATE = 'shr_',
  TAX_CODE = 'txcd_',
  TAX_RATE = 'txr_',
  TOKEN = 'tok_'
}

export enum StripeObjectTypes {
  BALANCE = 'balance',
  BALANCE_TRANSACTION = 'balance_transaction',
  BANK_ACCOUNT = 'bank_account',
  CARD = 'card',
  CASH_BALANCE = 'cash_balance',
  CASH_BALANCE_TRANSACTION = 'customer_cash_balance_transaction',
  CHARGE = 'charge',
  CHECKOUT_SESSION = 'checkout.session',
  CONFIRMATION_TOKEN = 'confirmation_token',
  COUPON = 'coupon',
  CUSTOMER = 'customer',
  CUSTOMER_SESSION = 'customer_session',
  DISCOUNT = 'discount',
  DISPUTE = 'dispute',
  EVENT = 'event',
  FILE = 'file',
  FILE_LINK = 'file_link',
  INVOICE = 'invoice',
  LIST = 'list',
  MANDATE = 'mandate',
  PAYMENT_INTENT = 'payment_intent',
  PAYMENT_METHOD = 'payment_method',
  PAYMENT_METHOD_CONFIGURATION = 'payment_method_configuration',
  PAYMENT_METHOD_DOMAIN = 'payment_method_domain',
  PAYMENT_LINK = 'payment_link',
  PAYOUT = 'payout',
  PRICE = 'price',
  PRODUCT = 'product',
  PROMOTION_CODE = 'promotion_code',
  REFUND = 'refund',
  SETUP_ATTEMPT = 'setup_attempt',
  SETUP_INTENT = 'setup_intent',
  SHIPPING_RATE = 'shipping_rate',
  TAX_CODE = 'tax_code',
  TAX_RATE = 'tax_rate',
  TOKEN = 'token'
}
